---
- name: Install HAProxy Packages
  package:
    name: "{{ item }}"
    state: "installed"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items: "{{ haproxy_distro_packages }}"

- name: Create haproxy conf.d dir
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "0755"
  with_items:
    - { path: "/etc/haproxy" }
    - { path: "/etc/haproxy/conf.d" }

      #- name: Get files in conf.d directory
      #  find:
      #    path: "/etc/haproxy/conf.d"
      #  register: conf_files
      #
      #- name: Ensure conf.d directory is empty
      #  file:
      #    path: "{{ item.path }}"
      #    state: absent
      #  with_items: "{{ conf_files.files }}"

- name: Ensure runtime directory exists
  file:
    path: "/run/haproxy"
    state: directory
    owner: haproxy
    group: haproxy

- name: Create tmpfiles entry
  copy:
    content: "d /run/haproxy 2775 haproxy haproxy -"
    dest: "/etc/tmpfiles.d/haproxy.conf"
