---
- name: Install HAProxy Packages
  package:
    name: "{{ item }}"
    state: "installed"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items: "{{ haproxy_distro_packages }}"

- name: Create haproxy conf.d dir
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "0755"
  with_items:
    - { path: "/etc/haproxy" }
    - { path: "/etc/haproxy/conf.d" }

- include: install_hatop.yml
  when: haproxy_install_hatop
