---
- name: "Create haproxy service config files"
  template:
    src: service.j2
    dest: "/etc/haproxy/conf.d/{{ item.service.haproxy_service_name }}"
  with_items: "{{ haproxy_service_configs | default([]) }}"

  notify: Restart haproxy

- name: Prevent SELinux from preventing haproxy from binding to arbitrary ports
  seboolean:
    name: haproxy_connect_any
    state: yes
    persistent: yes
  notify:
    - Restart haproxy
  when:
    - ansible_pkg_mgr == 'yum'
