---
- name: Get files in conf.d directory
  find: 
    path: "/etc/haproxy/conf.d"
  register: conf_files

- name: Empty conf.d directory
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ conf_files.files }}"

- name: Create haproxy service config files
  template:
    src: service.j2
    dest: "/etc/haproxy/conf.d/{{ '%02d' % (item.0 + 1) }}-{{ item.1.service.name }}"
#    dest: "/etc/haproxy/conf.d/test"
  with_indexed_items: "{{ haproxy_services | default([]) }}"
  notify: Restart haproxy
  
- name: Prevent SELinux from preventing haproxy from binding to arbitrary ports
  seboolean:
    name: haproxy_connect_any
    state: yes
    persistent: yes
  notify:
    - Restart haproxy
  when:
    - ansible_pkg_mgr == 'yum'
