---
- name: Restart haproxy
  systemd:
    name: "haproxy"
    state: "restarted"
    enabled: "yes"
  retries: 5

- name: restart haproxy_exporter
  systemd:
    daemon_reload: yes
    name: haproxy_exporter
    state: restarted
    enabled: yes
