---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: Restart haproxy
  service:
    name: "haproxy"
    state: "restarted"
    enabled: "yes"
  retries: 5

- name: restart haproxy_exporter
  service:
    name: haproxy_exporter
    state: restarted
    enabled: yes
